{
 "title": "Mefuzz dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Testcase queue current size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "testcase_count_in_queue_current",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Fuzzer count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "fuzzer_count_current", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Up",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Evalers",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "evaler_count_current", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Average database bulk saving duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(testcase_bulk_saving_duration_seconds_sum[1m])/rate(testcase_bulk_saving_duration_seconds_count[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}