global:
  scrape_interval:     5s
  evaluation_interval: 5s
  external_labels:
    monitor: 'pinky-cloud'

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: mefuzz
    scrape_interval: 5s
    static_configs:
      - targets: ['mefuzz:9000']

  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'